sudo: required
dist: xenial
language: ruby
rvm:
  - 2.3.7
cache: bundler
services:
  - docker
env:
  global:
    - secure: TxZQPS7NdXGCu1bHyXe/USzUqPYqx4xijGR8/Jc0H4J23hL9j/PbZIbG/0IqMfs955a0shiSRh7u3uRfsCtmE3Ic0HwJmSly1K3ysFAW4lV7cDsJFIK4wObGe2mqR2ao3ahlilpoeVRanV4z33XpOirFfD61WNHuq0qhDTneR4453irFJYb6M4BQFbvqvtPcD1rO+UGmq3A5hO4U4kpHCY/1Bwp8R+zteDOZyu52y6yCXznWu2SPhMUeMHvqCwpGjv5KLEpLnbG09+KCqfY0TWQ4oZe6gVIFT1xQjEqNTq+tsRDueLucSN7A+42b6640T3FAijpybSJrEFvwJMFBTgXBwANpgbO1GQ/1tB5whBo42S5JPhubLmfFyyNm6/mSUPckykWWhWJ0NwXfHUrlNNbC9yvcNaLq0Vc2OKOYc4zsOiWk5/g5+WX3L3cxxdpmrN33Q8jOrbY8G3x+EWZqFDHE+Org7x/tvbGANahQwCNHZ3H+OrbT1ds9rmLcpQ6p8DxJWNW6kxWnBP6ykxyN3Ipb4fjOPckgGtIMcwvvOcrDAOaXWbW6vf3kS318/IM9mS+GNc26MYOp1wmRPNJwFqhIK/MMuKhB+YAIKKyulk0SyjblS4rkFV7lC+mGdaIbBGFX8ptEemfXbyT45iV36VQFmLC+7fVLIX3xQegjqPk=
    - secure: B5lpNYfSlWHWNL9vI8GkadywAgq/Y39KOMXVPvOM39My2HQ+7WHlxt2D5Zvbj6us83tUdyMi3uKlDrGGWYaIgaPZraYa1NTX60HINFuWS1GHe2lJ5lBxZr5PIA1p3XIIbycHp24GBBszfuAGzhyjzC0UyOuQkxEy8ZxLGdVxY47NO+03kftZZpnoZFhoaYp9XcknpBb65IRIws/Liwoq8SjJZSkUP6LKPp587Nu6rp/iIRf/UnN2MY060ZC/O0CyvABZGdXyNx46UF5yOlSJDAz32OeFSED3E/V7OjCuugd6LBAI8TIHeJsPWouTkIBRCW0WJQGkrmY6+OUODQtcmTdhCau9SrmCJe9NR3vo4Bq32XvY+Vlrj749NGyuQV2rhk9jW7spofpV7d1OiZVvQ6/7GqHSrgOrKgF7ksYOoV6iR2k+2w1CfqmAki34RbvlY1LlTvNxzACLV/+D4Aa3I5913/Z4/8zSLKbv5bzfjq+pru/F+qMTROjPlgI23V9yzX/1bFlfSFvhyh6dPaCgBUh4ios/euds2gZMcxekbSPu+WHAZtvSZ3pRdrAc/j83y5xr1w4dUUeQ6yoF82WNzgssyFl1J+9jTLaP68Lv07wu/uKeEufeZreeiMyeyQfjCCYtf/WbrgDjU4vkAyEhfbaDojY230yJ2FSSGkr28cM=
  matrix:
    - LATEST=0 PHP_VERSION=8.0 PHP_SHORT_VERSION=80 XDEBUG_VERSION=3.0.4
    - LATEST=1 PHP_VERSION=7.4 PHP_SHORT_VERSION=74 XDEBUG_VERSION=2.9.0
    - LATEST=0 PHP_VERSION=7.3 PHP_SHORT_VERSION=73 XDEBUG_VERSION=2.9.0
    - LATEST=0 PHP_VERSION=7.2 PHP_SHORT_VERSION=72 XDEBUG_VERSION=2.9.0
    - LATEST=0 PHP_VERSION=7.1 PHP_SHORT_VERSION=71 XDEBUG_VERSION=2.9.0
    - LATEST=0 PHP_VERSION=7.0 PHP_SHORT_VERSION=70 XDEBUG_VERSION=2.7.2

script:
  - bash docker-build.sh
  - bash docker-test.sh
before_deploy:
  - docker images
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
after_script:
  - docker images
